### ISSUE TITLE
make `rules_nixpkgs_java` work with bazel 7 and bzlmod

### ISSUE THREAD

**Issue by prednaz** [tweag/rules_nixpkgs#504]
```[tasklist]
### Tasks
- [ ] https://github.com/tweag/rules_nixpkgs/pull/497
- [ ] https://github.com/tweag/rules_nixpkgs/pull/503
- [ ] https://github.com/tweag/rules_nixpkgs/pull/499
- [ ] https://github.com/tweag/rules_nixpkgs/pull/498
```

**Comment by DolceTriade** [comment]
@prednaz Are there any tasks that I can help with?
